apiVersion: batch/v1
kind: CronJob
metadata:
  name: degradation-detector
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "common.selectorLabels" . | nindent 12 }}
        spec:
          securityContext:
            runAsNonRoot: true
          restartPolicy: Never
          # 12 hours
          activeDeadlineSeconds: 43200
          containers:
            - name: degradation-detector
              image: {{ .Values.images.degradationDetector }}
              resources:
                requests:
                  cpu: "1"
                  memory: 512Mi
                limits:
                  cpu: "1.5"
                  memory: 1Gi
              env:
                - name: SLACK_TOKEN
                  value: {{ .Values.slack.token | quote }}
                - name: BACKEND_URL
                  value: "http://backend:80"
          imagePullSecrets:
            - name: ghcr