version: "2"
linters:
  default: all
  disable:
    - depguard
    - varnamelen
    - cyclop
    - exhaustruct
    - gochecknoglobals
    - mnd
    - nlreturn
    - wrapcheck
    - gocognit
    - funlen
    - wsl
    - containedctx
    - godot
    - tagliatelle
    - nestif
    - lll
    - ireturn
    - gosec
    - gocyclo
    - testpackage
    - forbidigo
    - exhaustive
    - forcetypeassert
    - dogsled
    - nilerr
    - musttag
    - goconst
    - gochecknoinits
    - contextcheck
  settings:
    errcheck:
      check-type-assertions: true
    gocritic:
      enable-all: true
      disabled-checks:
        - paramTypeCombine
        - commentedOutCode
        - unnamedResult
        - hugeParam
        - rangeValCopy
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomodguard:
      blocked:
        modules:
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/google/uuid
              reason: gofrs' package is not go module
    govet:
      disable:
        - fieldalignment
      enable-all: true
      settings:
        shadow:
          strict: true
    staticcheck:
      checks:
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        source: //noinspection
      - linters:
          - errorlint
        source: ^\s+if _, ok := err\.\([^.]+\.InternalError\); ok {
      - linters:
          - bodyclose
          - dupl
          - noctx
          - wrapcheck
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      - linters:
          - revive
        text: 'var-naming:'
      - linters:
          - gocritic
        text: 'exitAfterDefer:'
      - linters:
          - staticcheck
        text: 'SA1019: "github.com/golang/protobuf/proto" is deprecated'
      - linters:
          - err113
        text: do not define dynamic errors
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 50
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
