defaultBaseImage: alpine:3.14

baseImageOverrides:
  github.com/JetBrains/ij-perf-report-aggregator/cmd/clickhouse: ghcr.io/jetbrains/ij-perf-report-aggregator/clickhouse@sha256:3c23f2deef974780ee381d8e75ecd9ccb8c14fe489e4017a3a1d8d68240fe45f