GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET https://buildserver.labs.intellij.net/guestAuth/app/rest/changes?locator=build:(id:57684587)
Authorization: Bearer {{token}}
Accept: application/json

###

GET http://buildserver.labs.intellij.net/app/rest/builds/id:57684587
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=buildType:(id:ijplatform_master_UltimateStartupPerfTestMac),status:SUCCESS,count:10&fields=count,href,nextHref,build(id,status,agent(name),artifact-dependencies(build(id,buildTypeId,finishDate)),artifacts(file(children(file(children(file(href)))))))
Authorization: Bearer {{token}}
Accept: application/json
###

GET http://buildserver.labs.intellij.net/app/rest/builds/?locator=artifactDependency:(to:(id:54117831),recursive:false)&fields=build(*)
Authorization: Bearer {{token}}
Accept: application/json
###

GET http://buildserver.labs.intellij.net/guestAuth/app/rest/builds/?locator=id:57684587&fields=build(*,revisions(*,revision(*,vcs-root-instance(*))))
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=id:55176443&fields=build(*,artifacts(*))
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/buildTypes/id:ijplatform_master_UltimateStartupPerfTestMac
Authorization: Bearer {{token}}
###