GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET https://buildserver.labs.intellij.net/guestAuth/app/rest/changes?locator=build:(id:57684587)
Authorization: Bearer {{token}}
Accept: application/json

###

GET http://buildserver.labs.intellij.net/app/rest/builds/id:57684587
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=buildType:(id:ijplatform_master_UltimateStartupPerfTestMac),status:SUCCESS,count:10&fields=count,href,nextHref,build(id,status,agent(name),artifact-dependencies(build(id,buildTypeId,finishDate)),artifacts(file(children(file(children(file(href)))))))
Authorization: Bearer {{token}}
Accept: application/json
###

GET http://buildserver.labs.intellij.net/app/rest/builds/?locator=artifactDependency:(to:(id:54117831),recursive:false)&fields=build(*)
Authorization: Bearer {{token}}
Accept: application/json
###

GET http://buildserver.labs.intellij.net/guestAuth/app/rest/builds/?locator=buildType:(id:ijplatform_master_UltimateStartupPerfTestMac),sinceDate:20200322T030103%2B0300&fields=build(*)
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?fields=count%2Chref%2CnextHref%2Cbuild%28id%2CstartDate%2Cstatus%2Cagent%28name%29%2Cartifacts%28file%28children%28file%28children%28file%28href%29%29%29%29%29%29%2Cartifact-dependencies%28build%28id%2CbuildTypeId%2CfinishDate%29%29%29&locator=buildType:(id:ijplatform_master_PhpStormStartupPerfTestWindows),count:500,sinceDate:20200214T140712%2B0100
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=id:67846840&fields=count,href,nextHref,build(id,startDate,status,agent(name),artifacts(file(children(file(children(file(href)))))),artifact-dependencies(build(id,buildTypeId,finishDate)))
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/buildTypes/id:ijplatform_master_UltimateStartupPerfTestMac
Authorization: Bearer {{token}}
###