GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET http://localhost:8428/api/v1/query?query=bootstrap_d{buildC1="192"}[5y]
Accept: application/json

###

GET http://localhost:8428/api/v1/query?query=median(bootstrap_d{product="IU",machine="zlata"}[5y]) by (buildC1)
Accept: application/json

###

GET http://localhost:8428/api/v1/query?query=median_over_time(bootstrap_d[5y])
Accept: application/json

###

GET http://localhost:8428/api/v1/query_range?query=bootstrap_d&start=1412028000&end=1569794400&step=86400
Accept: application/json

###
GET http://localhost:8428/api/v1/export?match[]={__name__!=""}

###
GET http://localhost:9044/info

###
GET http://localhost:9044/metrics?product=IU&machine=zlata

###
GET http://127.0.0.1:9044/groupedMetrics?product=IU&machine=zlata

###

GET https://buildserver.labs.intellij.net/app/rest/builds/id:54846099/artifacts/content/run/startup/startup-stats-startup.json
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=buildType:(id:ijplatform_master_UltimateStartupPerfTestMac),status:SUCCESS,count:500,sinceDate:1570093455&fields=count,href,nextHref,build(id,agent(name))
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=id:54846099&fields=build(*)
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/builds/?locator=id:54880237
Authorization: Bearer {{token}}
Accept: application/json
###

GET https://buildserver.labs.intellij.net/app/rest/buildTypes/id:ijplatform_master_UltimateStartupPerfTestMac
Authorization: Bearer {{token}}
###