/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Button: typeof import("openvue/button/Button.vue")["default"]
    Checkbox: typeof import("openvue/checkbox/Checkbox.vue")["default"]
    Column: typeof import("openvue/column/Column.vue")["default"]
    DataTable: typeof import("openvue/datatable/DataTable.vue")["default"]
    Dialog: typeof import("openvue/dialog/Dialog.vue")["default"]
    Dropdown: typeof import("openvue/dropdown/Dropdown.vue")["default"]
    InputNumber: typeof import("openvue/inputnumber/InputNumber.vue")["default"]
    InputText: typeof import("openvue/inputtext/InputText.vue")["default"]
    Message: typeof import("openvue/message/Message.vue")["default"]
    MultiSelect: typeof import("openvue/multiselect/MultiSelect.vue")["default"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    Slider: typeof import("openvue/slider/Slider.vue")["default"]
    SplitButton: typeof import("openvue/splitbutton/SplitButton.vue")["default"]
    Textarea: typeof import("openvue/textarea/Textarea.vue")["default"]
    Toolbar: typeof import("openvue/toolbar/Toolbar.vue")["default"]
    TreeSelect: typeof import("openvue/treeselect/TreeSelect.vue")["default"]
  }
}
