/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: (typeof import("primevue/accordion"))["default"]
    AccordionContent: (typeof import("primevue/accordioncontent"))["default"]
    AccordionHeader: (typeof import("primevue/accordionheader"))["default"]
    AccordionPanel: (typeof import("primevue/accordionpanel"))["default"]
    AccordionTab: (typeof import("primevue/accordiontab"))["default"]
    Button: (typeof import("primevue/button"))["default"]
    Calendar: (typeof import("primevue/calendar"))["default"]
    Card: (typeof import("primevue/card"))["default"]
    Checkbox: (typeof import("primevue/checkbox"))["default"]
    Column: (typeof import("primevue/column"))["default"]
    DataTable: (typeof import("primevue/datatable"))["default"]
    Date"primevue/datepicker"t("default"/datepicker"))["default"]
    DeferredContent: (typeof import("primevue/deferredcontent"))["default"]
    Dialog: (typeof import("primevue/dialog"))["default"]
    Dropdown: (typeof import("primevue/dropdown"))["default"]
    FloatLabel: (typeof import("primevue/floatlabel"))["default"]
    InputNumber: (typeof import("primevue/inputnumber"))["default"]
    InputSwitch: (typeof import("primevue/inputswitch"))["default"]
    InputText: (typeof import("primevue/inputtext"))["default"]
    Message: (typeof import("primevue/message"))["default"]
    MultiSelect: (typeof import("primevue/multiselect"))["default"]
    Popover: (typeof import("primevue/popover"))["default"]
    ScrollTop: (typeof import("primevue/scrolltop"))["default"]
    Select: (typeof import("primevue/select"))["default"]
    SelectButton: (typeof import("primevue/selectbutton"))["default"]
    Slider: (typeof import("primevue/slider"))["default"]
    SplitButton: (typeof import("primevue/splitbutton"))["default"]
    TabPanel: (typeof import("primevue/tabpanel"))["default"]
    TabView: (typeof import("primevue/tabview"))["default"]
    Textarea: (typeof import("primevue/textarea"))["default"]
    Toolbar: (typeof import("primevue/toolbar"))["default"]
    TreeSelect: (typeof import("primevue/treeselect"))["default"]
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
