export const MAIN_METRICS_SET = new Set()

export const MAIN_METRICS: string[] = [
  "indexingTimeWithoutPauses",
  "scanningTimeWithoutPauses",
  "dumbModeWithPauses",
  "vfs_initial_refresh",
  "build_compilation_duration",
  "globalInspections",
  "findUsages",
  "localInspections",
  "firstCodeAnalysis",
  "completion",
  "searchEverywhere",
  "showFileHistory",
  "%expandMainMenu",
  "%expandProjectMenu",
  "%expandEditorMenu",
  "FileStructurePopup",
  "createKotlinFile",
  "highlighting",
  "FileStructurePopup",
  "vcs-log-indexing",
  "startInlineRename",
  "debugRunConfiguration",
  "debugStep_into",
  "searchEverywhere_dialog_shown",
  "showQuickFixes",
  "createJavaFile",
]
