export const MAVEN_PROJECTS = [
  "project-import-maven-quarkus/measureStartup",
  "project-reimport-maven-quarkus/measureStartup",
  "project-import-from-cache-maven-quarkus/measureStartup",
  "project-import-maven-1000-modules/measureStartup",
  "project-import-maven-5000-modules/measureStartup",
  "project-import-maven-keycloak/measureStartup",
  "project-import-maven-javaee7/measureStartup",
  "project-import-maven-javaee8/measureStartup",
  "project-import-maven-jersey/measureStartup",
  "project-import-maven-flink/measureStartup",
  "project-import-maven-drill/measureStartup",
  "project-import-maven-azure-sdk-java/measureStartup",
  "project-import-maven-hive/measureStartup",
  "project-import-maven-quarkus-to-legacy-model/measureStartup",
  "project-import-maven-1000-modules-to-legacy-model/measureStartup",
]
