<template>
  <DashboardPage
    db-name="perfintDev"
    table="ruby"
    persistent-id="rubymine_dashboard"
    :with-installer="false"
    initial-machine="Linux EC2 C6id.8xlarge (32 vCPU Xeon, 64 GB)"
  >
    <section>
      <GroupProjectsChart
        label="Indexing Time"
        :measure="['indexingTimeWithoutPauses']"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Number Of Indexed Files"
        measure="numberOfIndexedFilesWritingIndexValue"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Number Of Indexed Files (up to date)"
        measure="numberOfIndexedFilesWithNothingToWrite"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Index Size"
        measure="indexSize"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Scanning"
        :measure="['scanning', 'scanningTimeWithoutPauses']"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="GC Pause, ms"
        measure="gcPause"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'GitLab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="GC Memory Collected, Mb"
        measure="freedMemoryByGC"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'GitLab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Time: Gitlab"
        :measure="[
          'processingTime#Ruby',
          'processingTime#JavaScript',
          'processingTime#Markdown',
          'processingTime#TypeScript',
          'processingTime#Vue.js',
          'processingTime#YAML',
          'processingTime#Slim',
          'processingTime#SQL',
          'processingTime#RHTML',
          'processingTime#RBS',
          'processingTime#JSON',
          'processingTime#Haml',
          'processingTime#Cucumber',
          'processingTime#CSS',
          'processingTime#SCSS',
        ]"
        :projects="['gitlab-project-test/indexing']"
        :aliases="['Gitlab']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Speed: Gitlab"
        :measure="[
          'processingSpeedAvg#Ruby',
          'processingSpeedAvg#JavaScript',
          'processingSpeedAvg#Markdown',
          'processingSpeedAvg#Vue.js',
          'processingSpeedAvg#YAML',
          'processingSpeedAvg#Slim',
          'processingSpeedAvg#SQL',
          'processingSpeedAvg#RBS',
          'processingSpeedAvg#JSON',
          'processingSpeedAvg#Haml',
          'processingSpeedAvg#Cucumber',
          'processingSpeedAvg#SCSS',
        ]"
        :projects="['gitlab-project-test/indexing']"
        :aliases="['Gitlab']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Time: Diaspora"
        :measure="[
          'processingTime#Ruby',
          'processingTime#JavaScript',
          'processingTime#Markdown',
          'processingTime#TypeScript',
          'processingTime#Vue.js',
          'processingTime#YAML',
          'processingTime#Slim',
          'processingTime#SQL',
          'processingTime#RHTML',
          'processingTime#RBS',
          'processingTime#JSON',
          'processingTime#Haml',
          'processingTime#Cucumber',
          'processingTime#CSS',
          'processingTime#SCSS',
        ]"
        :projects="['diaspora-project-test/indexing']"
        :aliases="['Diaspora']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Speed: Diaspora"
        :measure="['processingSpeedAvg#Ruby', 'processingSpeedAvg#JavaScript', 'processingSpeedAvg#YAML', 'processingSpeedAvg#RBS']"
        :projects="['diaspora-project-test/indexing']"
        :aliases="['Diaspora']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Time: RBS Collection"
        :measure="[
          'processingTime#Ruby',
          'processingTime#JavaScript',
          'processingTime#Markdown',
          'processingTime#TypeScript',
          'processingTime#Vue.js',
          'processingTime#YAML',
          'processingTime#Slim',
          'processingTime#SQL',
          'processingTime#RHTML',
          'processingTime#RBS',
          'processingTime#JSON',
          'processingTime#Haml',
          'processingTime#Cucumber',
          'processingTime#CSS',
          'processingTime#SCSS',
        ]"
        :projects="['gem-rbs-collection-indexing-test/indexing']"
        :aliases="['RBS Collection']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Speed: RBS Collection"
        :measure="[
          'processingSpeedAvg#Ruby',
          'processingSpeedAvg#JavaScript',
          'processingSpeedAvg#Markdown',
          'processingSpeedAvg#Vue.js',
          'processingSpeedAvg#YAML',
          'processingSpeedAvg#Slim',
          'processingSpeedAvg#RBS',
          'processingSpeedAvg#JSON',
          'processingSpeedAvg#Haml',
        ]"
        :projects="['gem-rbs-collection-indexing-test/indexing']"
        :aliases="['RBS Collection']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Time: Redmine"
        :measure="[
          'processingTime#Ruby',
          'processingTime#JavaScript',
          'processingTime#Markdown',
          'processingTime#TypeScript',
          'processingTime#Vue.js',
          'processingTime#YAML',
          'processingTime#Slim',
          'processingTime#SQL',
          'processingTime#RHTML',
          'processingTime#RBS',
          'processingTime#JSON',
          'processingTime#Haml',
          'processingTime#Cucumber',
          'processingTime#CSS',
          'processingTime#SCSS',
        ]"
        :projects="['redmine-project-test/indexing']"
        :aliases="['Redmine']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Processing Speed: Redmine"
        :measure="[
          'processingSpeedAvg#Ruby',
          'processingSpeedAvg#JavaScript',
          'processingSpeedAvg#Vue.js',
          'processingSpeedAvg#YAML',
          'processingSpeedAvg#Slim',
          'processingSpeedAvg#SQL',
          'processingSpeedAvg#RHTML',
          'processingSpeedAvg#RBS',
          'processingSpeedAvg#Haml',
          'processingSpeedAvg#Cucumber',
        ]"
        :projects="['redmine-project-test/indexing']"
        :aliases="['Redmine']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Lexing Time, Diaspora, ms"
        :measure="[
          'lexingTime#CSS',
          'lexingTime#CoffeeScript',
          'lexingTime#ECMAScript.6',
          'lexingTime#Flow.JS',
          'lexingTime#GenericSQL',
          'lexingTime#HTML',
          'lexingTime#Haml',
          'lexingTime#JSON',
          'lexingTime#Markdown',
          'lexingTime#PostCSS',
          'lexingTime#RHTML',
          'lexingTime#SCSS',
          'lexingTime#TypeScript',
          'lexingTime#Vue',
          'lexingTime#ruby',
          'lexingTime#ruby.rbs',
          'lexingTime#yaml',
        ]"
        :projects="['diaspora-project-test/indexing']"
        :aliases="['Diaspora']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Lexing Time, RBS Collection, ms"
        :measure="[
          'lexingTime#CSS',
          'lexingTime#CoffeeScript',
          'lexingTime#ECMAScript.6',
          'lexingTime#Flow.JS',
          'lexingTime#GenericSQL',
          'lexingTime#HTML',
          'lexingTime#Haml',
          'lexingTime#JSON',
          'lexingTime#Markdown',
          'lexingTime#PostCSS',
          'lexingTime#RHTML',
          'lexingTime#SCSS',
          'lexingTime#TypeScript',
          'lexingTime#Vue',
          'lexingTime#ruby',
          'lexingTime#ruby.rbs',
          'lexingTime#yaml',
        ]"
        :projects="['gem-rbs-collection-indexing-test/indexing']"
        :aliases="['RBS Collection']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Lexing Time, Gitlab, ms"
        :measure="[
          'lexingTime#CSS',
          'lexingTime#CoffeeScript',
          'lexingTime#ECMAScript.6',
          'lexingTime#Flow.JS',
          'lexingTime#GenericSQL',
          'lexingTime#HTML',
          'lexingTime#Haml',
          'lexingTime#JSON',
          'lexingTime#Markdown',
          'lexingTime#PostCSS',
          'lexingTime#RHTML',
          'lexingTime#SCSS',
          'lexingTime#TypeScript',
          'lexingTime#Vue',
          'lexingTime#ruby',
          'lexingTime#ruby.rbs',
          'lexingTime#yaml',
        ]"
        :projects="['gitlab-project-test/indexing']"
        :aliases="['GitLab']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Lexing Time, Redmine, ms"
        :measure="[
          'lexingTime#CSS',
          'lexingTime#CoffeeScript',
          'lexingTime#ECMAScript.6',
          'lexingTime#Flow.JS',
          'lexingTime#GenericSQL',
          'lexingTime#HTML',
          'lexingTime#Haml',
          'lexingTime#JSON',
          'lexingTime#Markdown',
          'lexingTime#PostCSS',
          'lexingTime#RHTML',
          'lexingTime#SCSS',
          'lexingTime#TypeScript',
          'lexingTime#Vue',
          'lexingTime#ruby',
          'lexingTime#ruby.rbs',
          'lexingTime#yaml',
        ]"
        :projects="['redmine-project-test/indexing']"
        :aliases="['Redmine']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Parsing Time, Diaspora, ms"
        :measure="[
          'parsingTime#CSS',
          'parsingTime#CoffeeScript',
          'parsingTime#ECMAScript.6',
          'parsingTime#Flow.JS',
          'parsingTime#GenericSQL',
          'parsingTime#HTML',
          'parsingTime#Haml',
          'parsingTime#JSON',
          'parsingTime#Markdown',
          'parsingTime#PostCSS',
          'parsingTime#RHTML',
          'parsingTime#SCSS',
          'parsingTime#TypeScript',
          'parsingTime#Vue',
          'parsingTime#ruby',
          'parsingTime#ruby.rbs',
          'parsingTime#yaml',
        ]"
        :projects="['diaspora-project-test/indexing']"
        :aliases="['Diaspora']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Parsing Time, RBS Collection, ms"
        :measure="[
          'parsingTime#CSS',
          'parsingTime#CoffeeScript',
          'parsingTime#ECMAScript.6',
          'parsingTime#Flow.JS',
          'parsingTime#GenericSQL',
          'parsingTime#HTML',
          'parsingTime#Haml',
          'parsingTime#JSON',
          'parsingTime#Markdown',
          'parsingTime#PostCSS',
          'parsingTime#RHTML',
          'parsingTime#SCSS',
          'parsingTime#TypeScript',
          'parsingTime#Vue',
          'parsingTime#ruby',
          'parsingTime#ruby.rbs',
          'parsingTime#yaml',
        ]"
        :projects="['gem-rbs-collection-indexing-test/indexing']"
        :aliases="['RBS Collection']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Parsing Time, Gitlab, ms"
        :measure="[
          'parsingTime#CSS',
          'parsingTime#CoffeeScript',
          'parsingTime#ECMAScript.6',
          'parsingTime#Flow.JS',
          'parsingTime#GenericSQL',
          'parsingTime#HTML',
          'parsingTime#Haml',
          'parsingTime#JSON',
          'parsingTime#Markdown',
          'parsingTime#PostCSS',
          'parsingTime#RHTML',
          'parsingTime#SCSS',
          'parsingTime#TypeScript',
          'parsingTime#Vue',
          'parsingTime#ruby',
          'parsingTime#ruby.rbs',
          'parsingTime#yaml',
        ]"
        :projects="['gitlab-project-test/indexing']"
        :aliases="['GitLab']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Parsing Time, Redmine, ms"
        :measure="[
          'parsingTime#CSS',
          'parsingTime#CoffeeScript',
          'parsingTime#ECMAScript.6',
          'parsingTime#Flow.JS',
          'parsingTime#GenericSQL',
          'parsingTime#HTML',
          'parsingTime#Haml',
          'parsingTime#JSON',
          'parsingTime#Markdown',
          'parsingTime#PostCSS',
          'parsingTime#RHTML',
          'parsingTime#SCSS',
          'parsingTime#TypeScript',
          'parsingTime#Vue',
          'parsingTime#ruby',
          'parsingTime#ruby.rbs',
          'parsingTime#yaml',
        ]"
        :projects="['redmine-project-test/indexing']"
        :aliases="['Redmine']"
      />
    </section>
    <section>
      <GroupProjectsChart
        label="Indexing Time (With Data Before 11/07/2023)"
        :measure="['indexing', 'indexingTimeWithoutPauses']"
        :projects="[
          'diaspora-project-test/indexing',
          'gem-rbs-collection-indexing-test/indexing',
          'gitlab-project-test/indexing',
          'redmine-project-test/indexing',
          'markus-project-test/indexing',
          'mastodon-project-test/indexing',
          'rubygems-org-project-test/indexing',
        ]"
        :aliases="['Diaspora', 'RBS Collection', 'Gitlab', 'Redmine', 'Markus', 'Mastodon', 'RubyGems.org']"
      />
    </section>
  </DashboardPage>
</template>

<script setup lang="ts">
import GroupProjectsChart from "../charts/GroupProjectsChart.vue"
import DashboardPage from "../common/DashboardPage.vue"
</script>
