// Code generated by qtc from "metrics.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/analyzer/metrics.qtpl:1
package analyzer

//line pkg/analyzer/metrics.qtpl:1
import "report-aggregator/pkg/model"

// amCharts doesn't like 0 or -1 values for logarithmic axis, so, such values are skipped
//

//line pkg/analyzer/metrics.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/analyzer/metrics.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/analyzer/metrics.qtpl:6
func StreamDurationMetrics(qw422016 *qt422016.Writer, m *model.DurationEventMetrics) {
//line pkg/analyzer/metrics.qtpl:6
	qw422016.N().S(`{`)
//line pkg/analyzer/metrics.qtpl:8
	if m.Bootstrap > 0 {
//line pkg/analyzer/metrics.qtpl:8
		qw422016.N().S(`"bootstrap":`)
//line pkg/analyzer/metrics.qtpl:9
		qw422016.N().D(m.Bootstrap)
//line pkg/analyzer/metrics.qtpl:9
		qw422016.N().S(`,`)
//line pkg/analyzer/metrics.qtpl:10
	}
//line pkg/analyzer/metrics.qtpl:10
	qw422016.N().S(`"appInitPreparation":`)
//line pkg/analyzer/metrics.qtpl:12
	qw422016.N().D(m.AppInitPreparation)
//line pkg/analyzer/metrics.qtpl:12
	qw422016.N().S(`,"appInit":`)
//line pkg/analyzer/metrics.qtpl:13
	qw422016.N().D(m.AppInit)
//line pkg/analyzer/metrics.qtpl:13
	qw422016.N().S(`,"pluginDescriptorLoading":`)
//line pkg/analyzer/metrics.qtpl:14
	qw422016.N().D(m.PluginDescriptorLoading)
//line pkg/analyzer/metrics.qtpl:14
	qw422016.N().S(`,"appComponentCreation":`)
//line pkg/analyzer/metrics.qtpl:16
	qw422016.N().D(m.AppComponentCreation)
//line pkg/analyzer/metrics.qtpl:16
	qw422016.N().S(`,"projectComponentCreation":`)
//line pkg/analyzer/metrics.qtpl:17
	qw422016.N().D(m.ProjectComponentCreation)
//line pkg/analyzer/metrics.qtpl:19
	if m.ModuleLoading > 0 {
//line pkg/analyzer/metrics.qtpl:19
		qw422016.N().S(`,"moduleLoading":`)
//line pkg/analyzer/metrics.qtpl:21
		qw422016.N().D(m.ModuleLoading)
//line pkg/analyzer/metrics.qtpl:22
	}
//line pkg/analyzer/metrics.qtpl:22
	qw422016.N().S(`}`)
//line pkg/analyzer/metrics.qtpl:24
}

//line pkg/analyzer/metrics.qtpl:24
func WriteDurationMetrics(qq422016 qtio422016.Writer, m *model.DurationEventMetrics) {
//line pkg/analyzer/metrics.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/analyzer/metrics.qtpl:24
	StreamDurationMetrics(qw422016, m)
//line pkg/analyzer/metrics.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line pkg/analyzer/metrics.qtpl:24
}

//line pkg/analyzer/metrics.qtpl:24
func DurationMetrics(m *model.DurationEventMetrics) string {
//line pkg/analyzer/metrics.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/analyzer/metrics.qtpl:24
	WriteDurationMetrics(qb422016, m)
//line pkg/analyzer/metrics.qtpl:24
	qs422016 := string(qb422016.B)
//line pkg/analyzer/metrics.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/analyzer/metrics.qtpl:24
	return qs422016
//line pkg/analyzer/metrics.qtpl:24
}

//line pkg/analyzer/metrics.qtpl:26
func StreamInstantEventMetrics(qw422016 *qt422016.Writer, m *model.InstantEventMetrics) {
//line pkg/analyzer/metrics.qtpl:26
	qw422016.N().S(`{`)
//line pkg/analyzer/metrics.qtpl:28
	if m.Splash > 0 {
//line pkg/analyzer/metrics.qtpl:28
		qw422016.N().S(`"splash":`)
//line pkg/analyzer/metrics.qtpl:29
		qw422016.N().D(m.Splash)
//line pkg/analyzer/metrics.qtpl:29
		qw422016.N().S(`,`)
//line pkg/analyzer/metrics.qtpl:30
	}
//line pkg/analyzer/metrics.qtpl:30
	qw422016.N().S(`"startUpCompleted":`)
//line pkg/analyzer/metrics.qtpl:32
	qw422016.N().D(m.StartUpCompleted)
//line pkg/analyzer/metrics.qtpl:32
	qw422016.N().S(`}`)
//line pkg/analyzer/metrics.qtpl:34
}

//line pkg/analyzer/metrics.qtpl:34
func WriteInstantEventMetrics(qq422016 qtio422016.Writer, m *model.InstantEventMetrics) {
//line pkg/analyzer/metrics.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/analyzer/metrics.qtpl:34
	StreamInstantEventMetrics(qw422016, m)
//line pkg/analyzer/metrics.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line pkg/analyzer/metrics.qtpl:34
}

//line pkg/analyzer/metrics.qtpl:34
func InstantEventMetrics(m *model.InstantEventMetrics) string {
//line pkg/analyzer/metrics.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/analyzer/metrics.qtpl:34
	WriteInstantEventMetrics(qb422016, m)
//line pkg/analyzer/metrics.qtpl:34
	qs422016 := string(qb422016.B)
//line pkg/analyzer/metrics.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/analyzer/metrics.qtpl:34
	return qs422016
//line pkg/analyzer/metrics.qtpl:34
}
