// Code generated by qtc from "tcProperties.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line cmd/tc-collector/tcProperties.qtpl:1
package main

//line cmd/tc-collector/tcProperties.qtpl:3
import "github.com/magiconair/properties"

//line cmd/tc-collector/tcProperties.qtpl:4
import "github.com/asaskevich/govalidator"

//line cmd/tc-collector/tcProperties.qtpl:5
import "sort"

//line cmd/tc-collector/tcProperties.qtpl:8
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line cmd/tc-collector/tcProperties.qtpl:8
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line cmd/tc-collector/tcProperties.qtpl:8
func StreamPropertiesToJson(qw422016 *qt422016.Writer, p *properties.Properties) {
//line cmd/tc-collector/tcProperties.qtpl:8
	qw422016.N().S(`{`)
//line cmd/tc-collector/tcProperties.qtpl:11
	keys := p.Keys()
	sort.Strings(keys)

//line cmd/tc-collector/tcProperties.qtpl:14
	for i, key := range keys {
//line cmd/tc-collector/tcProperties.qtpl:16
		if isExcludedProperty(key) {
			continue
		}
		v := p.GetString(key, "")
		if len(v) == 0 {
			continue
		}

//line cmd/tc-collector/tcProperties.qtpl:25
		if i != 0 {
//line cmd/tc-collector/tcProperties.qtpl:25
			qw422016.N().S(`,`)
//line cmd/tc-collector/tcProperties.qtpl:25
		}
//line cmd/tc-collector/tcProperties.qtpl:25
		qw422016.N().S(`"`)
//line cmd/tc-collector/tcProperties.qtpl:27
		qw422016.N().S(key)
//line cmd/tc-collector/tcProperties.qtpl:27
		qw422016.N().S(`":`)
//line cmd/tc-collector/tcProperties.qtpl:28
		if v == "true" || v == "false" || govalidator.IsInt(v) {
//line cmd/tc-collector/tcProperties.qtpl:29
			qw422016.N().S(v)
//line cmd/tc-collector/tcProperties.qtpl:30
		} else {
//line cmd/tc-collector/tcProperties.qtpl:31
			qw422016.N().Q(v)
//line cmd/tc-collector/tcProperties.qtpl:32
		}
//line cmd/tc-collector/tcProperties.qtpl:33
	}
//line cmd/tc-collector/tcProperties.qtpl:33
	qw422016.N().S(`}`)
//line cmd/tc-collector/tcProperties.qtpl:35
}

//line cmd/tc-collector/tcProperties.qtpl:35
func WritePropertiesToJson(qq422016 qtio422016.Writer, p *properties.Properties) {
//line cmd/tc-collector/tcProperties.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line cmd/tc-collector/tcProperties.qtpl:35
	StreamPropertiesToJson(qw422016, p)
//line cmd/tc-collector/tcProperties.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line cmd/tc-collector/tcProperties.qtpl:35
}

//line cmd/tc-collector/tcProperties.qtpl:35
func PropertiesToJson(p *properties.Properties) string {
//line cmd/tc-collector/tcProperties.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line cmd/tc-collector/tcProperties.qtpl:35
	WritePropertiesToJson(qb422016, p)
//line cmd/tc-collector/tcProperties.qtpl:35
	qs422016 := string(qb422016.B)
//line cmd/tc-collector/tcProperties.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line cmd/tc-collector/tcProperties.qtpl:35
	return qs422016
//line cmd/tc-collector/tcProperties.qtpl:35
}
