// Code generated by qtc from "tcProperties.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/teamcity/tcProperties.qtpl:1
package main

//line pkg/teamcity/tcProperties.qtpl:1
import "github.com/magiconair/properties"

//line pkg/teamcity/tcProperties.qtpl:2
import "github.com/asaskevich/govalidator"

//line pkg/teamcity/tcProperties.qtpl:3
import "sort"

//line pkg/teamcity/tcProperties.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/teamcity/tcProperties.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/teamcity/tcProperties.qtpl:6
func StreamPropertiesToJson(qw422016 *qt422016.Writer, p *properties.Properties) {
//line pkg/teamcity/tcProperties.qtpl:6
	qw422016.N().S(`{`)
//line pkg/teamcity/tcProperties.qtpl:9
	keys := p.Keys()
	sort.Strings(keys)

//line pkg/teamcity/tcProperties.qtpl:12
	for i, key := range keys {
//line pkg/teamcity/tcProperties.qtpl:14
		if isExcludedProperty(key) {
			continue
		}
		v := p.GetString(key, "")
		if len(v) == 0 {
			continue
		}

//line pkg/teamcity/tcProperties.qtpl:23
		if i != 0 {
//line pkg/teamcity/tcProperties.qtpl:23
			qw422016.N().S(`,`)
//line pkg/teamcity/tcProperties.qtpl:23
		}
//line pkg/teamcity/tcProperties.qtpl:23
		qw422016.N().S(`"`)
//line pkg/teamcity/tcProperties.qtpl:25
		qw422016.N().S(key)
//line pkg/teamcity/tcProperties.qtpl:25
		qw422016.N().S(`":`)
//line pkg/teamcity/tcProperties.qtpl:26
		if v == "true" || v == "false" || govalidator.IsInt(v) {
//line pkg/teamcity/tcProperties.qtpl:27
			qw422016.N().S(v)
//line pkg/teamcity/tcProperties.qtpl:28
		} else {
//line pkg/teamcity/tcProperties.qtpl:29
			qw422016.N().Q(v)
//line pkg/teamcity/tcProperties.qtpl:30
		}
//line pkg/teamcity/tcProperties.qtpl:31
	}
//line pkg/teamcity/tcProperties.qtpl:31
	qw422016.N().S(`}`)
//line pkg/teamcity/tcProperties.qtpl:33
}

//line pkg/teamcity/tcProperties.qtpl:33
func WritePropertiesToJson(qq422016 qtio422016.Writer, p *properties.Properties) {
//line pkg/teamcity/tcProperties.qtpl:33
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/teamcity/tcProperties.qtpl:33
	StreamPropertiesToJson(qw422016, p)
//line pkg/teamcity/tcProperties.qtpl:33
	qt422016.ReleaseWriter(qw422016)
//line pkg/teamcity/tcProperties.qtpl:33
}

//line pkg/teamcity/tcProperties.qtpl:33
func PropertiesToJson(p *properties.Properties) string {
//line pkg/teamcity/tcProperties.qtpl:33
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/teamcity/tcProperties.qtpl:33
	WritePropertiesToJson(qb422016, p)
//line pkg/teamcity/tcProperties.qtpl:33
	qs422016 := string(qb422016.B)
//line pkg/teamcity/tcProperties.qtpl:33
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/teamcity/tcProperties.qtpl:33
	return qs422016
//line pkg/teamcity/tcProperties.qtpl:33
}
