name: Junie

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  junie:
    uses: JetBrains/junie-workflows/.github/workflows/ej-issue.yml@main